-- AlterTable
ALTER TABLE "DailyUsage" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "FaceSwap" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GeneratedImage" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GeneratedVideo" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ImageAnalysis" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ImageEdit" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Influencer" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Upscaled" ALTER COLUMN "creditUsed" SET DEFAULT 0,
ALTER COLUMN "creditUsed" SET DATA TYPE DOUBLE PRECISION;
