import Image from "next/image";

const showcase = [
  {
    title: "UGC Testimonial",
    subtitle: "Product review video",
    image: "/showcase/ugc-testimonial.jpg",
  },
  {
    title: "Lifestyle Content",
    subtitle: "Travel & daily life posts",
    image: "/showcase/lifestyle.jpg",
  },
  {
    title: "Product Marketing",
    subtitle: "Ads, reviews & promotions",
    image: "/showcase/product-marketing.jpg",
  },
  {
    title: "Fashion & Beauty",
    subtitle: "Outfits, looks & style tips",
    image: "/showcase/fashion-beauty.jpg",
  },
  {
    title: "Talking Head",
    subtitle: "Direct-to-camera content",
    image: "/showcase/talking-head.jpg",
  },
];

export const LandingContent = () => {
  return (
    <section id="examples" className="mx-auto w-full max-w-6xl px-6 pb-20 pt-6">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-5">
        {showcase.map((item) => (
          <article
            key={item.title}
            className="group overflow-hidden rounded-2xl border border-white/10 bg-[#0b0d19] transition hover:border-indigo-400/50"
          >
            <div className="relative h-72 w-full overflow-hidden">
              <Image
                src={item.image}
                alt={item.title}
                fill
                className="object-cover transition duration-500 group-hover:scale-105"
              />
            </div>
            <div className="p-4">
              <h3 className="text-lg font-bold text-white">{item.title}</h3>
              <p className="text-sm text-zinc-400">{item.subtitle}</p>
            </div>
          </article>
        ))}
      </div>

      <p className="mt-6 text-center text-sm text-zinc-500">
        All content generated by AI influencers built on Tavira Labs.
      </p>
    </section>
  );
};
