-- CreateEnum
CREATE TYPE "OnboardingStep" AS ENUM ('WELCOME', 'TOOL_INTRO', 'BILLING_PROMPT', 'LORA_TRAINING_INTRO', 'LORA_TRAINING_START', 'IMAGE_GENERATION_INTRO', 'VIDEO_GENERATION_START', 'IMAGE_GENERATION_START', 'COMPLETE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "onboardingStep" "OnboardingStep" DEFAULT 'WELCOME';
